notifications:
  email: false

rvm:
  - 2.1.2

matrix:
  include:
    - rvm: 2.1.2
      env: "RAILS_VERSION=4.0.9"
    - rvm: 2.0.0
      env: "RAILS_VERSION=4.1.5"
    - rvm: 1.9.3
      env: "RAILS_VERSION=4.1.5"
    - rvm: jruby
      env: "RAILS_VERSION=4.1.5 JRUBY_OPTS=\"-J-Xms512m -J-Xmx1024m\""
    - rvm: 2.1.2
      env: "RAILS_VERSION=4.2.0.beta1"
  allow_failures:
    - env: "RAILS_VERSION=4.2.0.beta1"

before_install:
  - gem install bundler

env:
 - "RAILS_VERSION=3.2.19"
 - "RAILS_VERSION=4.1.5"

notifications:
  irc: "irc.freenode.org#blacklight"
  email:
      - blacklight-commits@googlegroups.com

global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
